export interface PhraseCategory {
  role: string
  phrases: string[]
}

export const phraseLibrary: PhraseCategory[] = [
  {
    role: "Software Engineer",
    phrases: [
      "Reduced deployment time by 60% by implementing CI/CD pipeline with GitHub Actions and Docker",
      "Architected microservices migration that improved system scalability to handle 10x traffic increase",
      "Led code review process for team of 8 engineers, reducing production bugs by 35%",
      "Optimized database queries resulting in 40% improvement in API response times",
      "Built real-time notification system serving 500K+ daily active users using WebSockets",
      "Mentored 3 junior developers through structured pair programming and code review sessions",
      "Implemented automated testing suite achieving 92% code coverage across 200+ components",
      "Designed and shipped RESTful API consumed by 15+ internal and external clients",
      "Reduced cloud infrastructure costs by 30% through resource optimization and auto-scaling",
      "Led migration from monolithic architecture to event-driven microservices using Kafka",
      "Developed feature flagging system enabling safe deployment of 50+ experiments per quarter",
      "Improved page load time by 45% through code splitting, lazy loading, and CDN optimization",
    ],
  },
  {
    role: "Product Manager",
    phrases: [
      "Launched product feature that drove 25% increase in monthly active users within first quarter",
      "Defined product roadmap aligned with company OKRs, delivering 12 major features on schedule",
      "Conducted 50+ user interviews to validate product-market fit and prioritize feature backlog",
      "Increased user retention by 18% through data-driven redesign of onboarding experience",
      "Managed cross-functional team of 10 across engineering, design, and marketing",
      "Reduced customer churn by 22% by identifying and addressing top 5 pain points through analytics",
      "Grew product revenue from $2M to $5M ARR through strategic pricing and packaging changes",
      "Led A/B testing program that improved conversion rate by 30% across key user flows",
      "Defined and tracked KPIs resulting in 40% improvement in team delivery velocity",
      "Facilitated sprint planning and retrospectives for agile team of 8 engineers",
      "Prioritized backlog of 200+ feature requests using RICE scoring framework",
    ],
  },
  {
    role: "Marketing Manager",
    phrases: [
      "Increased organic traffic by 150% through SEO strategy and content marketing program",
      "Managed $500K annual marketing budget with 3.5x average return on ad spend",
      "Launched email marketing campaigns achieving 45% open rate and 12% click-through rate",
      "Grew social media following by 200% across LinkedIn, Twitter, and Instagram in 12 months",
      "Developed brand positioning strategy that increased brand awareness by 35% in target market",
      "Led product launch campaign generating 10,000+ qualified leads in first month",
      "Implemented marketing automation workflows reducing manual tasks by 60%",
      "Created content strategy producing 50+ blog posts, 20 whitepapers, and 10 webinars annually",
      "Improved lead-to-customer conversion rate by 25% through nurture campaign optimization",
      "Managed team of 5 marketers and 3 agencies across digital, content, and events",
      "Reduced customer acquisition cost by 40% through channel mix optimization",
    ],
  },
  {
    role: "Data Analyst",
    phrases: [
      "Built automated reporting dashboards in Tableau serving 50+ stakeholders across 5 departments",
      "Identified $2M in cost savings through analysis of operational inefficiencies",
      "Developed predictive model achieving 85% accuracy in forecasting customer churn",
      "Reduced manual reporting time by 80% through Python automation scripts",
      "Analyzed customer behavior data to inform product decisions impacting 1M+ users",
      "Created A/B testing framework that standardized experimentation across the organization",
      "Designed ETL pipelines processing 10M+ records daily using SQL and Python",
      "Delivered weekly executive business reviews with actionable insights and recommendations",
      "Improved data quality by 40% through implementation of validation rules and monitoring",
      "Conducted cohort analysis revealing key drivers of 30% increase in user engagement",
    ],
  },
  {
    role: "Project Manager",
    phrases: [
      "Delivered $3M digital transformation project on time and 10% under budget",
      "Managed portfolio of 8 concurrent projects with combined budget of $5M",
      "Reduced project delivery time by 25% through implementation of agile methodologies",
      "Coordinated cross-functional teams of 20+ members across 3 time zones",
      "Achieved 95% stakeholder satisfaction score through proactive communication and risk management",
      "Implemented project tracking system that improved resource utilization by 30%",
      "Led vendor selection and contract negotiation saving $200K annually",
      "Developed risk mitigation strategies that prevented 3 major project delays",
      "Facilitated weekly status meetings and prepared executive progress reports for C-suite",
      "Trained team of 15 on project management best practices and tools",
    ],
  },
  {
    role: "Sales Representative",
    phrases: [
      "Exceeded annual sales quota by 130%, generating $2.5M in new business revenue",
      "Built and maintained pipeline of 100+ qualified prospects through cold outreach and networking",
      "Closed largest enterprise deal in company history worth $500K ARR",
      "Reduced sales cycle by 20% through implementation of consultative selling approach",
      "Onboarded 50+ new accounts with 95% first-year retention rate",
      "Developed territory strategy resulting in 40% year-over-year revenue growth",
      "Conducted 200+ product demos and presentations to C-level executives",
      "Collaborated with marketing to create sales enablement materials increasing close rate by 15%",
      "Mentored 4 new sales representatives who all achieved quota within first 6 months",
      "Managed key account relationships generating $1M+ in upsell and cross-sell revenue",
    ],
  },
  {
    role: "Customer Success Manager",
    phrases: [
      "Managed portfolio of 50+ enterprise accounts with combined ARR of $8M",
      "Achieved 97% customer retention rate and 120% net revenue retention",
      "Increased customer NPS score from 35 to 65 through proactive engagement programs",
      "Drove $1.2M in expansion revenue through strategic upsell and cross-sell initiatives",
      "Reduced time-to-value by 40% through redesigned onboarding program",
      "Built customer health scoring model that predicted churn with 80% accuracy",
      "Created customer advocacy program generating 25 case studies and 15 referrals annually",
      "Led quarterly business reviews with executive stakeholders at Fortune 500 accounts",
      "Developed automated customer lifecycle workflows reducing manual touchpoints by 50%",
      "Trained team of 6 CSMs on best practices for account management and renewal strategy",
    ],
  },
  {
    role: "UX Designer",
    phrases: [
      "Redesigned checkout flow increasing conversion rate by 35% across web and mobile",
      "Conducted 100+ user interviews and usability tests to inform product design decisions",
      "Created design system with 80+ reusable components adopted by 3 product teams",
      "Reduced user task completion time by 50% through information architecture improvements",
      "Led design for product feature used by 2M+ monthly active users",
      "Improved accessibility compliance to WCAG 2.1 AA across all product surfaces",
      "Facilitated design sprints that reduced concept-to-prototype time from 4 weeks to 1 week",
      "Developed user personas and journey maps that aligned 5 cross-functional teams",
      "Increased mobile app store rating from 3.2 to 4.5 stars through UX improvements",
      "Created prototype library in Figma that reduced design iteration time by 60%",
    ],
  },
  {
    role: "DevOps Engineer",
    phrases: [
      "Achieved 99.99% uptime SLA by implementing robust monitoring and auto-healing infrastructure",
      "Reduced infrastructure costs by 45% through cloud resource optimization and reserved instances",
      "Built Kubernetes-based container orchestration platform serving 200+ microservices",
      "Implemented infrastructure-as-code using Terraform, managing 500+ cloud resources",
      "Reduced mean time to recovery from 4 hours to 15 minutes through automated incident response",
      "Built CI/CD pipeline processing 500+ deployments per week with zero-downtime releases",
      "Implemented security scanning in CI pipeline catching 95% of vulnerabilities before production",
      "Migrated 50+ applications from on-premises to AWS, reducing operational overhead by 60%",
      "Designed disaster recovery strategy with RPO of 1 hour and RTO of 30 minutes",
      "Automated infrastructure provisioning reducing environment setup from 2 days to 30 minutes",
    ],
  },
  {
    role: "HR Manager",
    phrases: [
      "Reduced employee turnover by 25% through implementation of engagement and retention programs",
      "Led recruitment strategy that filled 100+ positions with average time-to-hire of 30 days",
      "Designed and launched company-wide DEI initiative increasing diverse hires by 40%",
      "Implemented HRIS system streamlining HR processes and reducing administrative tasks by 50%",
      "Developed performance review framework adopted across organization of 500+ employees",
      "Managed annual compensation review ensuring 95% of adjustments aligned with market data",
      "Created employee onboarding program that improved new hire satisfaction by 30%",
      "Led organizational restructuring affecting 200+ employees with minimal disruption",
      "Built learning and development program with 50+ courses achieving 85% completion rate",
      "Reduced hiring costs by 35% through employee referral program generating 40% of hires",
    ],
  },
  {
    role: "Financial Analyst",
    phrases: [
      "Built financial models that guided $10M capital allocation decisions for executive team",
      "Identified $3M in cost reduction opportunities through variance analysis and forecasting",
      "Automated monthly reporting process reducing preparation time from 5 days to 1 day",
      "Developed rolling 12-month forecast model with 95% accuracy for revenue projections",
      "Presented quarterly financial analysis to board of directors and senior leadership",
      "Led annual budgeting process across 8 departments with combined budget of $50M",
      "Improved cash flow management resulting in $500K reduction in working capital requirements",
      "Created investor presentation materials for successful $15M Series B fundraise",
      "Conducted due diligence analysis for 3 potential acquisitions totaling $20M",
      "Implemented new FP&A tools that improved team productivity by 40%",
    ],
  },
  {
    role: "Operations Manager",
    phrases: [
      "Streamlined operations processes reducing costs by 20% while maintaining quality standards",
      "Managed team of 30+ employees across warehouse, logistics, and customer service",
      "Implemented lean manufacturing principles reducing waste by 35% and improving throughput",
      "Reduced order fulfillment time by 50% through process automation and workflow optimization",
      "Achieved 99.5% on-time delivery rate serving 10,000+ monthly orders",
      "Negotiated vendor contracts saving $400K annually while improving service levels",
      "Led ISO 9001 certification process ensuring compliance across all operational areas",
      "Designed inventory management system reducing stockouts by 60% and carrying costs by 25%",
      "Implemented safety program that reduced workplace incidents by 70% year-over-year",
      "Developed KPI dashboards providing real-time visibility into operational performance",
    ],
  },
  {
    role: "Content Writer",
    phrases: [
      "Produced 200+ blog posts generating 500K+ organic pageviews and 10K+ email subscribers",
      "Increased organic search traffic by 180% through SEO-optimized content strategy",
      "Wrote product copy that contributed to 25% increase in landing page conversion rates",
      "Managed editorial calendar across blog, social media, and email channels",
      "Developed brand voice guidelines adopted by marketing team of 10+ writers",
      "Created long-form content pieces ranking on page 1 of Google for 50+ target keywords",
      "Wrote case studies and whitepapers that supported $2M in pipeline generation",
      "Reduced content production cycle from 2 weeks to 5 days through streamlined workflows",
      "Launched company newsletter growing to 25K subscribers with 40% average open rate",
      "Collaborated with design team to produce infographics achieving 300% more social shares",
    ],
  },
  {
    role: "Business Analyst",
    phrases: [
      "Gathered and documented requirements for 15+ software projects with 95% stakeholder approval",
      "Created process flow diagrams and data models that reduced development rework by 30%",
      "Led gap analysis identifying 20 improvement opportunities saving $500K annually",
      "Facilitated workshops with 30+ stakeholders to align on project vision and scope",
      "Developed business cases for 5 strategic initiatives with combined ROI of 300%",
      "Implemented agile methodology across 3 teams improving delivery predictability by 40%",
      "Created user acceptance testing plans with 200+ test cases ensuring quality delivery",
      "Analyzed customer feedback data to prioritize product enhancements impacting 100K+ users",
      "Built automated reporting solutions using SQL and Power BI serving 20+ departments",
      "Managed vendor evaluation process selecting optimal solutions from 10+ candidates",
    ],
  },
  {
    role: "Graphic Designer",
    phrases: [
      "Designed brand identity system including logo, typography, and color palette for 5+ clients",
      "Created marketing collateral generating 40% increase in event attendance and lead capture",
      "Produced 500+ social media graphics achieving 200% improvement in engagement metrics",
      "Led redesign of company website improving user engagement by 60% and reducing bounce rate",
      "Developed packaging designs for product line generating $1M+ in retail sales",
      "Created presentation templates used by 100+ employees across the organization",
      "Managed design projects from concept to delivery for 20+ clients simultaneously",
      "Built brand style guide ensuring visual consistency across all marketing channels",
      "Produced video content and motion graphics achieving 1M+ views on social platforms",
      "Reduced design revision cycles by 40% through improved client communication process",
    ],
  },
]

export function searchPhrases(query: string): PhraseCategory[] {
  if (!query.trim()) return phraseLibrary
  const lower = query.toLowerCase()
  return phraseLibrary
    .map((cat) => ({
      ...cat,
      phrases: cat.role.toLowerCase().includes(lower)
        ? cat.phrases
        : cat.phrases.filter((p) => p.toLowerCase().includes(lower)),
    }))
    .filter((cat) => cat.phrases.length > 0)
}
